# Generated by Django 2.0.2 on 2018-02-18 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=512)),
                ('post_body', models.CharField(blank=True, max_length=2048)),
                ('post_image', models.URLField(blank=True)),
                ('post_datetime', models.DateTimeField(auto_now_add=True)),
                ('connect_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyPost',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_body', models.CharField(max_length=2048)),
                ('reply_datetime', models.DateTimeField(auto_now_add=True)),
                ('connect_count', models.PositiveSmallIntegerField(default=0)),
                ('parent_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Forum.ReplyPost')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.ForumPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
