# Generated by Django 2.0.2 on 2018-02-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20180221_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replypost',
            name='parent_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.ReplyPost'),
        ),
    ]
