# Generated by Django 2.0.2 on 2018-02-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20180222_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replypost',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Forum.ReplyPost'),
        ),
    ]
